version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: post294
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data: